# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20190606_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('origin', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=70)),
                ('capacity', models.IntegerField(default=0)),
                ('charges', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='bus_pics/'),
        ),
    ]
